name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go mod download
      - name: Deadcode
        run: go run golang.org/x/tools/cmd/deadcode@v0.45.0 -test ./...
      - uses: golangci/golangci-lint-action@v7
        with:
          version: v2.7.2
      - run: ./scripts/check-coverage.sh 90
